# Generated by Django 5.0.6 on 2024-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='resume',
            field=models.FileField(null=True, upload_to='static/media/applycant_resume'),
        ),
    ]
